modLoader="javafml"
loaderVersion="[4,)" # JavaFML spec 4+ is used by NeoForge 1.21.x
license="MIT"

[[mods]]
modId="bulksell"
version="${file.jarVersion}"
displayName="BulkSell"
author="You"
description='''
Sell bulk blocks for emeralds via a simple GUI.
'''

[[dependencies.bulksell]]
modId="neoforge"
mandatory=true
versionRange="[21.1,22.0)" # Accept any 21.1.x version
ordering="NONE"
side="BOTH"

[[dependencies.bulksell]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)" # Accept any 1.21.x version
ordering="NONE"
side="BOTH"
